[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["tasks-lib", "tasks-api"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
